export const colors = [
  {
    targetHexColor: "#FF0000",
    difficulty: "easy",
    shades: [
      { hexColor: "#FF0000", isTargetHexColor: true },
      { hexColor: "#00FFFF", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#00FF00", isTargetHexColor: false },
      { hexColor: "#0000FF", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#0000FF",
    difficulty: "easy",
    shades: [
      { hexColor: "#0000FF", isTargetHexColor: true },
      { hexColor: "#FFFF00", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#FF0000", isTargetHexColor: false },
      { hexColor: "#00FF00", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#00FF00",
    difficulty: "easy",
    shades: [
      { hexColor: "#00FF00", isTargetHexColor: true },
      { hexColor: "#FF00FF", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#0000FF", isTargetHexColor: false },
      { hexColor: "#FF0000", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FFFF00",
    difficulty: "easy",
    shades: [
      { hexColor: "#FFFF00", isTargetHexColor: true },
      { hexColor: "#0000FF", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#00FFFF", isTargetHexColor: false },
      { hexColor: "#FF00FF", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FFA500",
    difficulty: "easy",
    shades: [
      { hexColor: "#FFA500", isTargetHexColor: true },
      { hexColor: "#005AFF", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#00FFA5", isTargetHexColor: false },
      { hexColor: "#A500FF", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#800080",
    difficulty: "easy",
    shades: [
      { hexColor: "#800080", isTargetHexColor: true },
      { hexColor: "#7FFF7F", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#808000", isTargetHexColor: false },
      { hexColor: "#008080", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF69B4",
    difficulty: "easy",
    shades: [
      { hexColor: "#FF69B4", isTargetHexColor: true },
      { hexColor: "#00964B", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#B4FF69", isTargetHexColor: false },
      { hexColor: "#69B4FF", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#A52A2A",
    difficulty: "easy",
    shades: [
      { hexColor: "#A52A2A", isTargetHexColor: true },
      { hexColor: "#5AD5D5", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#2AA52A", isTargetHexColor: false },
      { hexColor: "#2A2AA5", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#808080",
    difficulty: "easy",
    shades: [
      { hexColor: "#808080", isTargetHexColor: true },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#FF0000", isTargetHexColor: false },
      { hexColor: "#00FF00", isTargetHexColor: false },
      { hexColor: "#0000FF", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#00FFFF",
    difficulty: "easy",
    shades: [
      { hexColor: "#00FFFF", isTargetHexColor: true },
      { hexColor: "#FF0000", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#FF00FF", isTargetHexColor: false },
      { hexColor: "#FFFF00", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF00FF",
    difficulty: "easy",
    shades: [
      { hexColor: "#FF00FF", isTargetHexColor: true },
      { hexColor: "#00FF00", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#FFFF00", isTargetHexColor: false },
      { hexColor: "#00FFFF", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#BFFF00",
    difficulty: "easy",
    shades: [
      { hexColor: "#BFFF00", isTargetHexColor: true },
      { hexColor: "#4000FF", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#00BFFF", isTargetHexColor: false },
      { hexColor: "#FF00BF", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#008080",
    difficulty: "easy",
    shades: [
      { hexColor: "#008080", isTargetHexColor: true },
      { hexColor: "#FF7F7F", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#800080", isTargetHexColor: false },
      { hexColor: "#808000", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#4B0082",
    difficulty: "easy",
    shades: [
      { hexColor: "#4B0082", isTargetHexColor: true },
      { hexColor: "#B4FF7D", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#824B00", isTargetHexColor: false },
      { hexColor: "#00824B", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#EE82EE",
    difficulty: "easy",
    shades: [
      { hexColor: "#EE82EE", isTargetHexColor: true },
      { hexColor: "#117D11", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#EEEE82", isTargetHexColor: false },
      { hexColor: "#82EEEE", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#DC143C",
    difficulty: "easy",
    shades: [
      { hexColor: "#DC143C", isTargetHexColor: true },
      { hexColor: "#23EBC3", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#3CDC14", isTargetHexColor: false },
      { hexColor: "#143CDC", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#7FFF00",
    difficulty: "easy",
    shades: [
      { hexColor: "#7FFF00", isTargetHexColor: true },
      { hexColor: "#8000FF", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#007FFF", isTargetHexColor: false },
      { hexColor: "#FF007F", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#D2691E",
    difficulty: "easy",
    shades: [
      { hexColor: "#D2691E", isTargetHexColor: true },
      { hexColor: "#2D96E1", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#1ED269", isTargetHexColor: false },
      { hexColor: "#691ED2", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF4500",
    difficulty: "easy",
    shades: [
      { hexColor: "#FF4500", isTargetHexColor: true },
      { hexColor: "#00BAFF", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#00FF45", isTargetHexColor: false },
      { hexColor: "#4500FF", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#DAA520",
    difficulty: "easy",
    shades: [
      { hexColor: "#DAA520", isTargetHexColor: true },
      { hexColor: "#255ADF", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#20DAA5", isTargetHexColor: false },
      { hexColor: "#A520DA", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#ADFF2F",
    difficulty: "easy",
    shades: [
      { hexColor: "#ADFF2F", isTargetHexColor: true },
      { hexColor: "#5200D0", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#2FADFF", isTargetHexColor: false },
      { hexColor: "#FF2FAD", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#5F9EA0",
    difficulty: "easy",
    shades: [
      { hexColor: "#5F9EA0", isTargetHexColor: true },
      { hexColor: "#A0615F", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#A05F9E", isTargetHexColor: false },
      { hexColor: "#9EA05F", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#8B008B",
    difficulty: "easy",
    shades: [
      { hexColor: "#8B008B", isTargetHexColor: true },
      { hexColor: "#74FF74", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#8B8B00", isTargetHexColor: false },
      { hexColor: "#008B8B", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#2E8B57",
    difficulty: "easy",
    shades: [
      { hexColor: "#2E8B57", isTargetHexColor: true },
      { hexColor: "#D174A8", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#572E8B", isTargetHexColor: false },
      { hexColor: "#8B572E", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF6347",
    difficulty: "easy",
    shades: [
      { hexColor: "#FF6347", isTargetHexColor: true },
      { hexColor: "#009CB8", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#47FF63", isTargetHexColor: false },
      { hexColor: "#6347FF", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#00FA9A",
    difficulty: "easy",
    shades: [
      { hexColor: "#00FA9A", isTargetHexColor: true },
      { hexColor: "#FF0565", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#9A00FA", isTargetHexColor: false },
      { hexColor: "#FA9A00", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#4682B4",
    difficulty: "easy",
    shades: [
      { hexColor: "#4682B4", isTargetHexColor: true },
      { hexColor: "#B97D4B", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#B44682", isTargetHexColor: false },
      { hexColor: "#82B446", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#9ACD32",
    difficulty: "easy",
    shades: [
      { hexColor: "#9ACD32", isTargetHexColor: true },
      { hexColor: "#6532CD", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#329ACD", isTargetHexColor: false },
      { hexColor: "#CD329A", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#B22222",
    difficulty: "easy",
    shades: [
      { hexColor: "#B22222", isTargetHexColor: true },
      { hexColor: "#4DDDDD", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#22B222", isTargetHexColor: false },
      { hexColor: "#2222B2", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#20B2AA",
    difficulty: "easy",
    shades: [
      { hexColor: "#20B2AA", isTargetHexColor: true },
      { hexColor: "#DF4D55", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#AA20B2", isTargetHexColor: false },
      { hexColor: "#B2AA20", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#BA55D3",
    difficulty: "easy",
    shades: [
      { hexColor: "#BA55D3", isTargetHexColor: true },
      { hexColor: "#45AA2C", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#D3BA55", isTargetHexColor: false },
      { hexColor: "#55D3BA", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#32CD32",
    difficulty: "easy",
    shades: [
      { hexColor: "#32CD32", isTargetHexColor: true },
      { hexColor: "#CD32CD", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#3232CD", isTargetHexColor: false },
      { hexColor: "#CD3232", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FFD700",
    difficulty: "easy",
    shades: [
      { hexColor: "#FFD700", isTargetHexColor: true },
      { hexColor: "#0028FF", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#00FFD7", isTargetHexColor: false },
      { hexColor: "#D700FF", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#C71585",
    difficulty: "easy",
    shades: [
      { hexColor: "#C71585", isTargetHexColor: true },
      { hexColor: "#38EA7A", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#85C715", isTargetHexColor: false },
      { hexColor: "#1585C7", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#8A2BE2",
    difficulty: "easy",
    shades: [
      { hexColor: "#8A2BE2", isTargetHexColor: true },
      { hexColor: "#75D41D", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#E28A2B", isTargetHexColor: false },
      { hexColor: "#2BE28A", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#CD5C5C",
    difficulty: "easy",
    shades: [
      { hexColor: "#CD5C5C", isTargetHexColor: true },
      { hexColor: "#32A3A3", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#5CCD5C", isTargetHexColor: false },
      { hexColor: "#5C5CCD", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#F08080",
    difficulty: "easy",
    shades: [
      { hexColor: "#F08080", isTargetHexColor: true },
      { hexColor: "#0F7F7F", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#80F080", isTargetHexColor: false },
      { hexColor: "#8080F0", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FA8072",
    difficulty: "easy",
    shades: [
      { hexColor: "#FA8072", isTargetHexColor: true },
      { hexColor: "#057F8D", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#72FA80", isTargetHexColor: false },
      { hexColor: "#8072FA", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#E9967A",
    difficulty: "easy",
    shades: [
      { hexColor: "#E9967A", isTargetHexColor: true },
      { hexColor: "#166985", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#7AE996", isTargetHexColor: false },
      { hexColor: "#967AE9", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF1493",
    difficulty: "easy",
    shades: [
      { hexColor: "#FF1493", isTargetHexColor: true },
      { hexColor: "#00EB6C", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#93FF14", isTargetHexColor: false },
      { hexColor: "#1493FF", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#D8BFD8",
    difficulty: "easy",
    shades: [
      { hexColor: "#D8BFD8", isTargetHexColor: true },
      { hexColor: "#274027", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#D8D8BF", isTargetHexColor: false },
      { hexColor: "#BFD8D8", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#DB7093",
    difficulty: "easy",
    shades: [
      { hexColor: "#DB7093", isTargetHexColor: true },
      { hexColor: "#248F6C", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#93DB70", isTargetHexColor: false },
      { hexColor: "#7093DB", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#8B4513",
    difficulty: "easy",
    shades: [
      { hexColor: "#8B4513", isTargetHexColor: true },
      { hexColor: "#74BAEC", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#138B45", isTargetHexColor: false },
      { hexColor: "#45138B", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#DA70D6",
    difficulty: "easy",
    shades: [
      { hexColor: "#DA70D6", isTargetHexColor: true },
      { hexColor: "#258F29", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#D6DA70", isTargetHexColor: false },
      { hexColor: "#70D6DA", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#7B68EE",
    difficulty: "easy",
    shades: [
      { hexColor: "#7B68EE", isTargetHexColor: true },
      { hexColor: "#849711", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#EE7B68", isTargetHexColor: false },
      { hexColor: "#68EE7B", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#6A5ACD",
    difficulty: "easy",
    shades: [
      { hexColor: "#6A5ACD", isTargetHexColor: true },
      { hexColor: "#95A532", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#CD6A5A", isTargetHexColor: false },
      { hexColor: "#5ACD6A", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#483D8B",
    difficulty: "easy",
    shades: [
      { hexColor: "#483D8B", isTargetHexColor: true },
      { hexColor: "#B7C274", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#8B483D", isTargetHexColor: false },
      { hexColor: "#3D8B48", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#008B8B",
    difficulty: "easy",
    shades: [
      { hexColor: "#008B8B", isTargetHexColor: true },
      { hexColor: "#FF7474", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#8B008B", isTargetHexColor: false },
      { hexColor: "#8B8B00", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#556B2F",
    difficulty: "easy",
    shades: [
      { hexColor: "#556B2F", isTargetHexColor: true },
      { hexColor: "#AA94D0", isTargetHexColor: false },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#2F556B", isTargetHexColor: false },
      { hexColor: "#6B2F55", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#696969",
    difficulty: "easy",
    shades: [
      { hexColor: "#696969", isTargetHexColor: true },
      { hexColor: "#000000", isTargetHexColor: false },
      { hexColor: "#FFFFFF", isTargetHexColor: false },
      { hexColor: "#FF0000", isTargetHexColor: false },
      { hexColor: "#00FF00", isTargetHexColor: false },
      { hexColor: "#0000FF", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF0000",
    difficulty: "normal",
    shades: [
      { hexColor: "#FF0000", isTargetHexColor: true },
      { hexColor: "#F00000", isTargetHexColor: false },
      { hexColor: "#E10000", isTargetHexColor: false },
      { hexColor: "#D20000", isTargetHexColor: false },
      { hexColor: "#C30000", isTargetHexColor: false },
      { hexColor: "#B40000", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#0000FF",
    difficulty: "normal",
    shades: [
      { hexColor: "#0000FF", isTargetHexColor: true },
      { hexColor: "#0000F0", isTargetHexColor: false },
      { hexColor: "#0000E1", isTargetHexColor: false },
      { hexColor: "#0000D2", isTargetHexColor: false },
      { hexColor: "#0000C3", isTargetHexColor: false },
      { hexColor: "#0000B4", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#00FF00",
    difficulty: "normal",
    shades: [
      { hexColor: "#00FF00", isTargetHexColor: true },
      { hexColor: "#00F000", isTargetHexColor: false },
      { hexColor: "#00E100", isTargetHexColor: false },
      { hexColor: "#00D200", isTargetHexColor: false },
      { hexColor: "#00C300", isTargetHexColor: false },
      { hexColor: "#00B400", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FFFF00",
    difficulty: "normal",
    shades: [
      { hexColor: "#FFFF00", isTargetHexColor: true },
      { hexColor: "#F0F000", isTargetHexColor: false },
      { hexColor: "#E1E100", isTargetHexColor: false },
      { hexColor: "#D2D200", isTargetHexColor: false },
      { hexColor: "#C3C300", isTargetHexColor: false },
      { hexColor: "#B4B400", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FFA500",
    difficulty: "normal",
    shades: [
      { hexColor: "#FFA500", isTargetHexColor: true },
      { hexColor: "#F09600", isTargetHexColor: false },
      { hexColor: "#E18700", isTargetHexColor: false },
      { hexColor: "#D27800", isTargetHexColor: false },
      { hexColor: "#C36900", isTargetHexColor: false },
      { hexColor: "#B45A00", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#800080",
    difficulty: "normal",
    shades: [
      { hexColor: "#800080", isTargetHexColor: true },
      { hexColor: "#710071", isTargetHexColor: false },
      { hexColor: "#620062", isTargetHexColor: false },
      { hexColor: "#530053", isTargetHexColor: false },
      { hexColor: "#440044", isTargetHexColor: false },
      { hexColor: "#350035", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF69B4",
    difficulty: "normal",
    shades: [
      { hexColor: "#FF69B4", isTargetHexColor: true },
      { hexColor: "#F05AA5", isTargetHexColor: false },
      { hexColor: "#E14B96", isTargetHexColor: false },
      { hexColor: "#D23C87", isTargetHexColor: false },
      { hexColor: "#C32D78", isTargetHexColor: false },
      { hexColor: "#B41E69", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#A52A2A",
    difficulty: "normal",
    shades: [
      { hexColor: "#A52A2A", isTargetHexColor: true },
      { hexColor: "#961B1B", isTargetHexColor: false },
      { hexColor: "#870C0C", isTargetHexColor: false },
      { hexColor: "#780000", isTargetHexColor: false },
      { hexColor: "#690000", isTargetHexColor: false },
      { hexColor: "#5A0000", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#808080",
    difficulty: "normal",
    shades: [
      { hexColor: "#808080", isTargetHexColor: true },
      { hexColor: "#717171", isTargetHexColor: false },
      { hexColor: "#626262", isTargetHexColor: false },
      { hexColor: "#535353", isTargetHexColor: false },
      { hexColor: "#444444", isTargetHexColor: false },
      { hexColor: "#353535", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#00FFFF",
    difficulty: "normal",
    shades: [
      { hexColor: "#00FFFF", isTargetHexColor: true },
      { hexColor: "#00F0F0", isTargetHexColor: false },
      { hexColor: "#00E1E1", isTargetHexColor: false },
      { hexColor: "#00D2D2", isTargetHexColor: false },
      { hexColor: "#00C3C3", isTargetHexColor: false },
      { hexColor: "#00B4B4", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF00FF",
    difficulty: "normal",
    shades: [
      { hexColor: "#FF00FF", isTargetHexColor: true },
      { hexColor: "#F000F0", isTargetHexColor: false },
      { hexColor: "#E100E1", isTargetHexColor: false },
      { hexColor: "#D200D2", isTargetHexColor: false },
      { hexColor: "#C300C3", isTargetHexColor: false },
      { hexColor: "#B400B4", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#BFFF00",
    difficulty: "normal",
    shades: [
      { hexColor: "#BFFF00", isTargetHexColor: true },
      { hexColor: "#B0F000", isTargetHexColor: false },
      { hexColor: "#A1E100", isTargetHexColor: false },
      { hexColor: "#92D200", isTargetHexColor: false },
      { hexColor: "#83C300", isTargetHexColor: false },
      { hexColor: "#74B400", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#008080",
    difficulty: "normal",
    shades: [
      { hexColor: "#008080", isTargetHexColor: true },
      { hexColor: "#007171", isTargetHexColor: false },
      { hexColor: "#006262", isTargetHexColor: false },
      { hexColor: "#005353", isTargetHexColor: false },
      { hexColor: "#004444", isTargetHexColor: false },
      { hexColor: "#003535", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#4B0082",
    difficulty: "normal",
    shades: [
      { hexColor: "#4B0082", isTargetHexColor: true },
      { hexColor: "#3C0073", isTargetHexColor: false },
      { hexColor: "#2D0064", isTargetHexColor: false },
      { hexColor: "#1E0055", isTargetHexColor: false },
      { hexColor: "#0F0046", isTargetHexColor: false },
      { hexColor: "#000037", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#EE82EE",
    difficulty: "normal",
    shades: [
      { hexColor: "#EE82EE", isTargetHexColor: true },
      { hexColor: "#DF73DF", isTargetHexColor: false },
      { hexColor: "#D064D0", isTargetHexColor: false },
      { hexColor: "#C155C1", isTargetHexColor: false },
      { hexColor: "#B246B2", isTargetHexColor: false },
      { hexColor: "#A337A3", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#DC143C",
    difficulty: "normal",
    shades: [
      { hexColor: "#DC143C", isTargetHexColor: true },
      { hexColor: "#CD052D", isTargetHexColor: false },
      { hexColor: "#BE001E", isTargetHexColor: false },
      { hexColor: "#AF000F", isTargetHexColor: false },
      { hexColor: "#A00000", isTargetHexColor: false },
      { hexColor: "#910000", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#7FFF00",
    difficulty: "normal",
    shades: [
      { hexColor: "#7FFF00", isTargetHexColor: true },
      { hexColor: "#70F000", isTargetHexColor: false },
      { hexColor: "#61E100", isTargetHexColor: false },
      { hexColor: "#52D200", isTargetHexColor: false },
      { hexColor: "#43C300", isTargetHexColor: false },
      { hexColor: "#34B400", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#D2691E",
    difficulty: "normal",
    shades: [
      { hexColor: "#D2691E", isTargetHexColor: true },
      { hexColor: "#C35A0F", isTargetHexColor: false },
      { hexColor: "#B44B00", isTargetHexColor: false },
      { hexColor: "#A53C00", isTargetHexColor: false },
      { hexColor: "#962D00", isTargetHexColor: false },
      { hexColor: "#871E00", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF4500",
    difficulty: "normal",
    shades: [
      { hexColor: "#FF4500", isTargetHexColor: true },
      { hexColor: "#F03600", isTargetHexColor: false },
      { hexColor: "#E12700", isTargetHexColor: false },
      { hexColor: "#D21800", isTargetHexColor: false },
      { hexColor: "#C30900", isTargetHexColor: false },
      { hexColor: "#B40000", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#DAA520",
    difficulty: "normal",
    shades: [
      { hexColor: "#DAA520", isTargetHexColor: true },
      { hexColor: "#CB9611", isTargetHexColor: false },
      { hexColor: "#BC8702", isTargetHexColor: false },
      { hexColor: "#AD7800", isTargetHexColor: false },
      { hexColor: "#9E6900", isTargetHexColor: false },
      { hexColor: "#8F5A00", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#ADFF2F",
    difficulty: "normal",
    shades: [
      { hexColor: "#ADFF2F", isTargetHexColor: true },
      { hexColor: "#9EF020", isTargetHexColor: false },
      { hexColor: "#8FE111", isTargetHexColor: false },
      { hexColor: "#80D202", isTargetHexColor: false },
      { hexColor: "#71C300", isTargetHexColor: false },
      { hexColor: "#62B400", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#5F9EA0",
    difficulty: "normal",
    shades: [
      { hexColor: "#5F9EA0", isTargetHexColor: true },
      { hexColor: "#508F91", isTargetHexColor: false },
      { hexColor: "#418082", isTargetHexColor: false },
      { hexColor: "#327173", isTargetHexColor: false },
      { hexColor: "#236264", isTargetHexColor: false },
      { hexColor: "#145355", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#8B008B",
    difficulty: "normal",
    shades: [
      { hexColor: "#8B008B", isTargetHexColor: true },
      { hexColor: "#7C007C", isTargetHexColor: false },
      { hexColor: "#6D006D", isTargetHexColor: false },
      { hexColor: "#5E005E", isTargetHexColor: false },
      { hexColor: "#4F004F", isTargetHexColor: false },
      { hexColor: "#400040", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#2E8B57",
    difficulty: "normal",
    shades: [
      { hexColor: "#2E8B57", isTargetHexColor: true },
      { hexColor: "#1F7C48", isTargetHexColor: false },
      { hexColor: "#106D39", isTargetHexColor: false },
      { hexColor: "#015E2A", isTargetHexColor: false },
      { hexColor: "#004F1B", isTargetHexColor: false },
      { hexColor: "#00400C", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF6347",
    difficulty: "normal",
    shades: [
      { hexColor: "#FF6347", isTargetHexColor: true },
      { hexColor: "#F05438", isTargetHexColor: false },
      { hexColor: "#E14529", isTargetHexColor: false },
      { hexColor: "#D2361A", isTargetHexColor: false },
      { hexColor: "#C3270B", isTargetHexColor: false },
      { hexColor: "#B41800", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#00FA9A",
    difficulty: "normal",
    shades: [
      { hexColor: "#00FA9A", isTargetHexColor: true },
      { hexColor: "#00EB8B", isTargetHexColor: false },
      { hexColor: "#00DC7C", isTargetHexColor: false },
      { hexColor: "#00CD6D", isTargetHexColor: false },
      { hexColor: "#00BE5E", isTargetHexColor: false },
      { hexColor: "#00AF4F", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#4682B4",
    difficulty: "normal",
    shades: [
      { hexColor: "#4682B4", isTargetHexColor: true },
      { hexColor: "#3773A5", isTargetHexColor: false },
      { hexColor: "#286496", isTargetHexColor: false },
      { hexColor: "#195587", isTargetHexColor: false },
      { hexColor: "#0A4678", isTargetHexColor: false },
      { hexColor: "#003769", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#9ACD32",
    difficulty: "normal",
    shades: [
      { hexColor: "#9ACD32", isTargetHexColor: true },
      { hexColor: "#8BBE23", isTargetHexColor: false },
      { hexColor: "#7CAF14", isTargetHexColor: false },
      { hexColor: "#6DA005", isTargetHexColor: false },
      { hexColor: "#5E9100", isTargetHexColor: false },
      { hexColor: "#4F8200", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#B22222",
    difficulty: "normal",
    shades: [
      { hexColor: "#B22222", isTargetHexColor: true },
      { hexColor: "#A31313", isTargetHexColor: false },
      { hexColor: "#940404", isTargetHexColor: false },
      { hexColor: "#850000", isTargetHexColor: false },
      { hexColor: "#760000", isTargetHexColor: false },
      { hexColor: "#670000", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#20B2AA",
    difficulty: "normal",
    shades: [
      { hexColor: "#20B2AA", isTargetHexColor: true },
      { hexColor: "#11A39B", isTargetHexColor: false },
      { hexColor: "#02948C", isTargetHexColor: false },
      { hexColor: "#00857D", isTargetHexColor: false },
      { hexColor: "#00766E", isTargetHexColor: false },
      { hexColor: "#00675F", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#BA55D3",
    difficulty: "normal",
    shades: [
      { hexColor: "#BA55D3", isTargetHexColor: true },
      { hexColor: "#AB46C4", isTargetHexColor: false },
      { hexColor: "#9C37B5", isTargetHexColor: false },
      { hexColor: "#8D28A6", isTargetHexColor: false },
      { hexColor: "#7E1997", isTargetHexColor: false },
      { hexColor: "#6F0A88", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#32CD32",
    difficulty: "normal",
    shades: [
      { hexColor: "#32CD32", isTargetHexColor: true },
      { hexColor: "#23BE23", isTargetHexColor: false },
      { hexColor: "#14AF14", isTargetHexColor: false },
      { hexColor: "#05A005", isTargetHexColor: false },
      { hexColor: "#009100", isTargetHexColor: false },
      { hexColor: "#008200", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FFD700",
    difficulty: "normal",
    shades: [
      { hexColor: "#FFD700", isTargetHexColor: true },
      { hexColor: "#F0C800", isTargetHexColor: false },
      { hexColor: "#E1B900", isTargetHexColor: false },
      { hexColor: "#D2AA00", isTargetHexColor: false },
      { hexColor: "#C39B00", isTargetHexColor: false },
      { hexColor: "#B48C00", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#C71585",
    difficulty: "normal",
    shades: [
      { hexColor: "#C71585", isTargetHexColor: true },
      { hexColor: "#B80676", isTargetHexColor: false },
      { hexColor: "#A90067", isTargetHexColor: false },
      { hexColor: "#9A0058", isTargetHexColor: false },
      { hexColor: "#8B0049", isTargetHexColor: false },
      { hexColor: "#7C003A", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#8A2BE2",
    difficulty: "normal",
    shades: [
      { hexColor: "#8A2BE2", isTargetHexColor: true },
      { hexColor: "#7B1CD3", isTargetHexColor: false },
      { hexColor: "#6C0DC4", isTargetHexColor: false },
      { hexColor: "#5D00B5", isTargetHexColor: false },
      { hexColor: "#4E00A6", isTargetHexColor: false },
      { hexColor: "#3F0097", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#CD5C5C",
    difficulty: "normal",
    shades: [
      { hexColor: "#CD5C5C", isTargetHexColor: true },
      { hexColor: "#BE4D4D", isTargetHexColor: false },
      { hexColor: "#AF3E3E", isTargetHexColor: false },
      { hexColor: "#A02F2F", isTargetHexColor: false },
      { hexColor: "#912020", isTargetHexColor: false },
      { hexColor: "#821111", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#F08080",
    difficulty: "normal",
    shades: [
      { hexColor: "#F08080", isTargetHexColor: true },
      { hexColor: "#E17171", isTargetHexColor: false },
      { hexColor: "#D26262", isTargetHexColor: false },
      { hexColor: "#C35353", isTargetHexColor: false },
      { hexColor: "#B44444", isTargetHexColor: false },
      { hexColor: "#A53535", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FA8072",
    difficulty: "normal",
    shades: [
      { hexColor: "#FA8072", isTargetHexColor: true },
      { hexColor: "#EB7163", isTargetHexColor: false },
      { hexColor: "#DC6254", isTargetHexColor: false },
      { hexColor: "#CD5345", isTargetHexColor: false },
      { hexColor: "#BE4436", isTargetHexColor: false },
      { hexColor: "#AF3527", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#E9967A",
    difficulty: "normal",
    shades: [
      { hexColor: "#E9967A", isTargetHexColor: true },
      { hexColor: "#DA876B", isTargetHexColor: false },
      { hexColor: "#CB785C", isTargetHexColor: false },
      { hexColor: "#BC694D", isTargetHexColor: false },
      { hexColor: "#AD5A3E", isTargetHexColor: false },
      { hexColor: "#9E4B2F", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF1493",
    difficulty: "normal",
    shades: [
      { hexColor: "#FF1493", isTargetHexColor: true },
      { hexColor: "#F00584", isTargetHexColor: false },
      { hexColor: "#E10075", isTargetHexColor: false },
      { hexColor: "#D20066", isTargetHexColor: false },
      { hexColor: "#C30057", isTargetHexColor: false },
      { hexColor: "#B40048", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#D8BFD8",
    difficulty: "normal",
    shades: [
      { hexColor: "#D8BFD8", isTargetHexColor: true },
      { hexColor: "#C9B0C9", isTargetHexColor: false },
      { hexColor: "#BAA1BA", isTargetHexColor: false },
      { hexColor: "#AB92AB", isTargetHexColor: false },
      { hexColor: "#9C839C", isTargetHexColor: false },
      { hexColor: "#8D748D", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#DB7093",
    difficulty: "normal",
    shades: [
      { hexColor: "#DB7093", isTargetHexColor: true },
      { hexColor: "#CC6184", isTargetHexColor: false },
      { hexColor: "#BD5275", isTargetHexColor: false },
      { hexColor: "#AE4366", isTargetHexColor: false },
      { hexColor: "#9F3457", isTargetHexColor: false },
      { hexColor: "#902548", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#8B4513",
    difficulty: "normal",
    shades: [
      { hexColor: "#8B4513", isTargetHexColor: true },
      { hexColor: "#7C3604", isTargetHexColor: false },
      { hexColor: "#6D2700", isTargetHexColor: false },
      { hexColor: "#5E1800", isTargetHexColor: false },
      { hexColor: "#4F0900", isTargetHexColor: false },
      { hexColor: "#400000", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#DA70D6",
    difficulty: "normal",
    shades: [
      { hexColor: "#DA70D6", isTargetHexColor: true },
      { hexColor: "#CB61C7", isTargetHexColor: false },
      { hexColor: "#BC52B8", isTargetHexColor: false },
      { hexColor: "#AD43A9", isTargetHexColor: false },
      { hexColor: "#9E349A", isTargetHexColor: false },
      { hexColor: "#8F258B", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#7B68EE",
    difficulty: "normal",
    shades: [
      { hexColor: "#7B68EE", isTargetHexColor: true },
      { hexColor: "#6C59DF", isTargetHexColor: false },
      { hexColor: "#5D4AD0", isTargetHexColor: false },
      { hexColor: "#4E3BC1", isTargetHexColor: false },
      { hexColor: "#3F2CB2", isTargetHexColor: false },
      { hexColor: "#301DA3", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#6A5ACD",
    difficulty: "normal",
    shades: [
      { hexColor: "#6A5ACD", isTargetHexColor: true },
      { hexColor: "#5B4BBE", isTargetHexColor: false },
      { hexColor: "#4C3CAF", isTargetHexColor: false },
      { hexColor: "#3D2DA0", isTargetHexColor: false },
      { hexColor: "#2E1E91", isTargetHexColor: false },
      { hexColor: "#1F0F82", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#483D8B",
    difficulty: "normal",
    shades: [
      { hexColor: "#483D8B", isTargetHexColor: true },
      { hexColor: "#392E7C", isTargetHexColor: false },
      { hexColor: "#2A1F6D", isTargetHexColor: false },
      { hexColor: "#1B105E", isTargetHexColor: false },
      { hexColor: "#0C014F", isTargetHexColor: false },
      { hexColor: "#000040", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#008B8B",
    difficulty: "normal",
    shades: [
      { hexColor: "#008B8B", isTargetHexColor: true },
      { hexColor: "#007C7C", isTargetHexColor: false },
      { hexColor: "#006D6D", isTargetHexColor: false },
      { hexColor: "#005E5E", isTargetHexColor: false },
      { hexColor: "#004F4F", isTargetHexColor: false },
      { hexColor: "#004040", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#556B2F",
    difficulty: "normal",
    shades: [
      { hexColor: "#556B2F", isTargetHexColor: true },
      { hexColor: "#465C20", isTargetHexColor: false },
      { hexColor: "#374D11", isTargetHexColor: false },
      { hexColor: "#283E02", isTargetHexColor: false },
      { hexColor: "#192F00", isTargetHexColor: false },
      { hexColor: "#0A2000", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#696969",
    difficulty: "normal",
    shades: [
      { hexColor: "#696969", isTargetHexColor: true },
      { hexColor: "#5A5A5A", isTargetHexColor: false },
      { hexColor: "#4B4B4B", isTargetHexColor: false },
      { hexColor: "#3C3C3C", isTargetHexColor: false },
      { hexColor: "#2D2D2D", isTargetHexColor: false },
      { hexColor: "#1E1E1E", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF0000",
    difficulty: "hard",
    shades: [
      { hexColor: "#FF0000", isTargetHexColor: true },
      { hexColor: "#FA0000", isTargetHexColor: false },
      { hexColor: "#F50000", isTargetHexColor: false },
      { hexColor: "#F00000", isTargetHexColor: false },
      { hexColor: "#EB0000", isTargetHexColor: false },
      { hexColor: "#E60000", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#0000FF",
    difficulty: "hard",
    shades: [
      { hexColor: "#0000FF", isTargetHexColor: true },
      { hexColor: "#0000FA", isTargetHexColor: false },
      { hexColor: "#0000F5", isTargetHexColor: false },
      { hexColor: "#0000F0", isTargetHexColor: false },
      { hexColor: "#0000EB", isTargetHexColor: false },
      { hexColor: "#0000E6", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#00FF00",
    difficulty: "hard",
    shades: [
      { hexColor: "#00FF00", isTargetHexColor: true },
      { hexColor: "#00FA00", isTargetHexColor: false },
      { hexColor: "#00F500", isTargetHexColor: false },
      { hexColor: "#00F000", isTargetHexColor: false },
      { hexColor: "#00EB00", isTargetHexColor: false },
      { hexColor: "#00E600", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FFFF00",
    difficulty: "hard",
    shades: [
      { hexColor: "#FFFF00", isTargetHexColor: true },
      { hexColor: "#FAFA00", isTargetHexColor: false },
      { hexColor: "#F5F500", isTargetHexColor: false },
      { hexColor: "#F0F000", isTargetHexColor: false },
      { hexColor: "#EBEB00", isTargetHexColor: false },
      { hexColor: "#E6E600", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FFA500",
    difficulty: "hard",
    shades: [
      { hexColor: "#FFA500", isTargetHexColor: true },
      { hexColor: "#FAA000", isTargetHexColor: false },
      { hexColor: "#F59B00", isTargetHexColor: false },
      { hexColor: "#F09600", isTargetHexColor: false },
      { hexColor: "#EB9100", isTargetHexColor: false },
      { hexColor: "#E68C00", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#800080",
    difficulty: "hard",
    shades: [
      { hexColor: "#800080", isTargetHexColor: true },
      { hexColor: "#7B007B", isTargetHexColor: false },
      { hexColor: "#760076", isTargetHexColor: false },
      { hexColor: "#710071", isTargetHexColor: false },
      { hexColor: "#6C006C", isTargetHexColor: false },
      { hexColor: "#670067", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF69B4",
    difficulty: "hard",
    shades: [
      { hexColor: "#FF69B4", isTargetHexColor: true },
      { hexColor: "#FA64AF", isTargetHexColor: false },
      { hexColor: "#F55BAA", isTargetHexColor: false },
      { hexColor: "#F05AA5", isTargetHexColor: false },
      { hexColor: "#EB55A0", isTargetHexColor: false },
      { hexColor: "#E6509B", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#A52A2A",
    difficulty: "hard",
    shades: [
      { hexColor: "#A52A2A", isTargetHexColor: true },
      { hexColor: "#A02525", isTargetHexColor: false },
      { hexColor: "#9B2020", isTargetHexColor: false },
      { hexColor: "#961B1B", isTargetHexColor: false },
      { hexColor: "#911616", isTargetHexColor: false },
      { hexColor: "#8C1111", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#808080",
    difficulty: "hard",
    shades: [
      { hexColor: "#808080", isTargetHexColor: true },
      { hexColor: "#7B7B7B", isTargetHexColor: false },
      { hexColor: "#767676", isTargetHexColor: false },
      { hexColor: "#717171", isTargetHexColor: false },
      { hexColor: "#6C6C6C", isTargetHexColor: false },
      { hexColor: "#676767", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#00FFFF",
    difficulty: "hard",
    shades: [
      { hexColor: "#00FFFF", isTargetHexColor: true },
      { hexColor: "#00FAFA", isTargetHexColor: false },
      { hexColor: "#00F5F5", isTargetHexColor: false },
      { hexColor: "#00F0F0", isTargetHexColor: false },
      { hexColor: "#00EBEB", isTargetHexColor: false },
      { hexColor: "#00E6E6", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF00FF",
    difficulty: "hard",
    shades: [
      { hexColor: "#FF00FF", isTargetHexColor: true },
      { hexColor: "#FA00FA", isTargetHexColor: false },
      { hexColor: "#F500F5", isTargetHexColor: false },
      { hexColor: "#F000F0", isTargetHexColor: false },
      { hexColor: "#EB00EB", isTargetHexColor: false },
      { hexColor: "#E600E6", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#BFFF00",
    difficulty: "hard",
    shades: [
      { hexColor: "#BFFF00", isTargetHexColor: true },
      { hexColor: "#BAFA00", isTargetHexColor: false },
      { hexColor: "#B5F500", isTargetHexColor: false },
      { hexColor: "#B0F000", isTargetHexColor: false },
      { hexColor: "#ABEB00", isTargetHexColor: false },
      { hexColor: "#A6E600", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#008080",
    difficulty: "hard",
    shades: [
      { hexColor: "#008080", isTargetHexColor: true },
      { hexColor: "#007B7B", isTargetHexColor: false },
      { hexColor: "#007676", isTargetHexColor: false },
      { hexColor: "#007171", isTargetHexColor: false },
      { hexColor: "#006C6C", isTargetHexColor: false },
      { hexColor: "#006767", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#4B0082",
    difficulty: "hard",
    shades: [
      { hexColor: "#4B0082", isTargetHexColor: true },
      { hexColor: "#46007D", isTargetHexColor: false },
      { hexColor: "#410078", isTargetHexColor: false },
      { hexColor: "#3C0073", isTargetHexColor: false },
      { hexColor: "#37006E", isTargetHexColor: false },
      { hexColor: "#320069", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#EE82EE",
    difficulty: "hard",
    shades: [
      { hexColor: "#EE82EE", isTargetHexColor: true },
      { hexColor: "#E97DE9", isTargetHexColor: false },
      { hexColor: "#E478E4", isTargetHexColor: false },
      { hexColor: "#DF73DF", isTargetHexColor: false },
      { hexColor: "#DA6EDA", isTargetHexColor: false },
      { hexColor: "#D569D5", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#DC143C",
    difficulty: "hard",
    shades: [
      { hexColor: "#DC143C", isTargetHexColor: true },
      { hexColor: "#D70F37", isTargetHexColor: false },
      { hexColor: "#D20A32", isTargetHexColor: false },
      { hexColor: "#CD052D", isTargetHexColor: false },
      { hexColor: "#C80028", isTargetHexColor: false },
      { hexColor: "#C30023", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#7FFF00",
    difficulty: "hard",
    shades: [
      { hexColor: "#7FFF00", isTargetHexColor: true },
      { hexColor: "#7AFA00", isTargetHexColor: false },
      { hexColor: "#75F500", isTargetHexColor: false },
      { hexColor: "#70F000", isTargetHexColor: false },
      { hexColor: "#6BEB00", isTargetHexColor: false },
      { hexColor: "#66E600", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#D2691E",
    difficulty: "hard",
    shades: [
      { hexColor: "#D2691E", isTargetHexColor: true },
      { hexColor: "#CD6419", isTargetHexColor: false },
      { hexColor: "#C85F14", isTargetHexColor: false },
      { hexColor: "#C35A0F", isTargetHexColor: false },
      { hexColor: "#BE550A", isTargetHexColor: false },
      { hexColor: "#B95005", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF4500",
    difficulty: "hard",
    shades: [
      { hexColor: "#FF4500", isTargetHexColor: true },
      { hexColor: "#FA6400", isTargetHexColor: false },
      { hexColor: "#F53B00", isTargetHexColor: false },
      { hexColor: "#F03600", isTargetHexColor: false },
      { hexColor: "#EB3100", isTargetHexColor: false },
      { hexColor: "#E62C00", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#DAA520",
    difficulty: "hard",
    shades: [
      { hexColor: "#DAA520", isTargetHexColor: true },
      { hexColor: "#D5A01B", isTargetHexColor: false },
      { hexColor: "#D09B16", isTargetHexColor: false },
      { hexColor: "#CB9611", isTargetHexColor: false },
      { hexColor: "#C6910C", isTargetHexColor: false },
      { hexColor: "#C18C07", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#ADFF2F",
    difficulty: "hard",
    shades: [
      { hexColor: "#ADFF2F", isTargetHexColor: true },
      { hexColor: "#A8FA2A", isTargetHexColor: false },
      { hexColor: "#A3F525", isTargetHexColor: false },
      { hexColor: "#9EF020", isTargetHexColor: false },
      { hexColor: "#99EB1B", isTargetHexColor: false },
      { hexColor: "#94E616", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#5F9EA0",
    difficulty: "hard",
    shades: [
      { hexColor: "#5F9EA0", isTargetHexColor: true },
      { hexColor: "#5A999B", isTargetHexColor: false },
      { hexColor: "#559496", isTargetHexColor: false },
      { hexColor: "#508F91", isTargetHexColor: false },
      { hexColor: "#4B8A8C", isTargetHexColor: false },
      { hexColor: "#468587", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#8B008B",
    difficulty: "hard",
    shades: [
      { hexColor: "#8B008B", isTargetHexColor: true },
      { hexColor: "#860086", isTargetHexColor: false },
      { hexColor: "#810081", isTargetHexColor: false },
      { hexColor: "#7C007C", isTargetHexColor: false },
      { hexColor: "#770077", isTargetHexColor: false },
      { hexColor: "#720072", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#2E8B57",
    difficulty: "hard",
    shades: [
      { hexColor: "#2E8B57", isTargetHexColor: true },
      { hexColor: "#298652", isTargetHexColor: false },
      { hexColor: "#24814D", isTargetHexColor: false },
      { hexColor: "#1F7C48", isTargetHexColor: false },
      { hexColor: "#1A7743", isTargetHexColor: false },
      { hexColor: "#15723E", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF6347",
    difficulty: "hard",
    shades: [
      { hexColor: "#FF6347", isTargetHexColor: true },
      { hexColor: "#FA5E42", isTargetHexColor: false },
      { hexColor: "#F5593D", isTargetHexColor: false },
      { hexColor: "#F05438", isTargetHexColor: false },
      { hexColor: "#EB4F33", isTargetHexColor: false },
      { hexColor: "#E64A2E", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#00FA9A",
    difficulty: "hard",
    shades: [
      { hexColor: "#00FA9A", isTargetHexColor: true },
      { hexColor: "#00F595", isTargetHexColor: false },
      { hexColor: "#00F090", isTargetHexColor: false },
      { hexColor: "#00EB8B", isTargetHexColor: false },
      { hexColor: "#00E686", isTargetHexColor: false },
      { hexColor: "#00E081", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#4682B4",
    difficulty: "hard",
    shades: [
      { hexColor: "#4682B4", isTargetHexColor: true },
      { hexColor: "#417DAF", isTargetHexColor: false },
      { hexColor: "#3C78AA", isTargetHexColor: false },
      { hexColor: "#3773A5", isTargetHexColor: false },
      { hexColor: "#326EA0", isTargetHexColor: false },
      { hexColor: "#2D699B", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#9ACD32",
    difficulty: "hard",
    shades: [
      { hexColor: "#9ACD32", isTargetHexColor: true },
      { hexColor: "#95C82D", isTargetHexColor: false },
      { hexColor: "#90C328", isTargetHexColor: false },
      { hexColor: "#8BBE23", isTargetHexColor: false },
      { hexColor: "#86B91E", isTargetHexColor: false },
      { hexColor: "#81B419", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#B22222",
    difficulty: "hard",
    shades: [
      { hexColor: "#B22222", isTargetHexColor: true },
      { hexColor: "#AD1D1D", isTargetHexColor: false },
      { hexColor: "#A81818", isTargetHexColor: false },
      { hexColor: "#A31313", isTargetHexColor: false },
      { hexColor: "#9E0E0E", isTargetHexColor: false },
      { hexColor: "#990909", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#20B2AA",
    difficulty: "hard",
    shades: [
      { hexColor: "#20B2AA", isTargetHexColor: true },
      { hexColor: "#1BADA5", isTargetHexColor: false },
      { hexColor: "#16A8A0", isTargetHexColor: false },
      { hexColor: "#11A39B", isTargetHexColor: false },
      { hexColor: "#0C9E96", isTargetHexColor: false },
      { hexColor: "#079991", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#BA55D3",
    difficulty: "hard",
    shades: [
      { hexColor: "#BA55D3", isTargetHexColor: true },
      { hexColor: "#B550CE", isTargetHexColor: false },
      { hexColor: "#B04BC9", isTargetHexColor: false },
      { hexColor: "#AB46C4", isTargetHexColor: false },
      { hexColor: "#A641BF", isTargetHexColor: false },
      { hexColor: "#A13CBA", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#32CD32",
    difficulty: "hard",
    shades: [
      { hexColor: "#32CD32", isTargetHexColor: true },
      { hexColor: "#2DC82D", isTargetHexColor: false },
      { hexColor: "#28C328", isTargetHexColor: false },
      { hexColor: "#23BE23", isTargetHexColor: false },
      { hexColor: "#1EB91E", isTargetHexColor: false },
      { hexColor: "#19B419", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FFD700",
    difficulty: "hard",
    shades: [
      { hexColor: "#FFD700", isTargetHexColor: true },
      { hexColor: "#FAD200", isTargetHexColor: false },
      { hexColor: "#F5CD00", isTargetHexColor: false },
      { hexColor: "#F0C800", isTargetHexColor: false },
      { hexColor: "#EBC300", isTargetHexColor: false },
      { hexColor: "#E6BE00", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#C71585",
    difficulty: "hard",
    shades: [
      { hexColor: "#C71585", isTargetHexColor: true },
      { hexColor: "#C21080", isTargetHexColor: false },
      { hexColor: "#BD0B7B", isTargetHexColor: false },
      { hexColor: "#B80676", isTargetHexColor: false },
      { hexColor: "#B30171", isTargetHexColor: false },
      { hexColor: "#AE006C", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#8A2BE2",
    difficulty: "hard",
    shades: [
      { hexColor: "#8A2BE2", isTargetHexColor: true },
      { hexColor: "#8526DD", isTargetHexColor: false },
      { hexColor: "#8021D8", isTargetHexColor: false },
      { hexColor: "#7B1CD3", isTargetHexColor: false },
      { hexColor: "#7617CE", isTargetHexColor: false },
      { hexColor: "#7112C9", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#CD5C5C",
    difficulty: "hard",
    shades: [
      { hexColor: "#CD5C5C", isTargetHexColor: true },
      { hexColor: "#C85757", isTargetHexColor: false },
      { hexColor: "#C35252", isTargetHexColor: false },
      { hexColor: "#BE4D4D", isTargetHexColor: false },
      { hexColor: "#B94848", isTargetHexColor: false },
      { hexColor: "#B44343", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#F08080",
    difficulty: "hard",
    shades: [
      { hexColor: "#F08080", isTargetHexColor: true },
      { hexColor: "#EB7B7B", isTargetHexColor: false },
      { hexColor: "#E67676", isTargetHexColor: false },
      { hexColor: "#E17171", isTargetHexColor: false },
      { hexColor: "#DC6C6C", isTargetHexColor: false },
      { hexColor: "#D76767", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FA8072",
    difficulty: "hard",
    shades: [
      { hexColor: "#FA8072", isTargetHexColor: true },
      { hexColor: "#F57B6D", isTargetHexColor: false },
      { hexColor: "#F07668", isTargetHexColor: false },
      { hexColor: "#EB7163", isTargetHexColor: false },
      { hexColor: "#E66C5E", isTargetHexColor: false },
      { hexColor: "#E16759", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#E9967A",
    difficulty: "hard",
    shades: [
      { hexColor: "#E9967A", isTargetHexColor: true },
      { hexColor: "#E49175", isTargetHexColor: false },
      { hexColor: "#DF8C70", isTargetHexColor: false },
      { hexColor: "#DA876B", isTargetHexColor: false },
      { hexColor: "#D58266", isTargetHexColor: false },
      { hexColor: "#D07D61", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#FF1493",
    difficulty: "hard",
    shades: [
      { hexColor: "#FF1493", isTargetHexColor: true },
      { hexColor: "#FA0F8E", isTargetHexColor: false },
      { hexColor: "#F50A89", isTargetHexColor: false },
      { hexColor: "#F00584", isTargetHexColor: false },
      { hexColor: "#EB007F", isTargetHexColor: false },
      { hexColor: "#E6007A", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#D8BFD8",
    difficulty: "hard",
    shades: [
      { hexColor: "#D8BFD8", isTargetHexColor: true },
      { hexColor: "#D3BAD3", isTargetHexColor: false },
      { hexColor: "#CEB5CE", isTargetHexColor: false },
      { hexColor: "#C9B0C9", isTargetHexColor: false },
      { hexColor: "#C4ABC4", isTargetHexColor: false },
      { hexColor: "#BFA6BF", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#DB7093",
    difficulty: "hard",
    shades: [
      { hexColor: "#DB7093", isTargetHexColor: true },
      { hexColor: "#D66B8E", isTargetHexColor: false },
      { hexColor: "#D16689", isTargetHexColor: false },
      { hexColor: "#CC6184", isTargetHexColor: false },
      { hexColor: "#C75C7F", isTargetHexColor: false },
      { hexColor: "#C2577A", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#8B4513",
    difficulty: "hard",
    shades: [
      { hexColor: "#8B4513", isTargetHexColor: true },
      { hexColor: "#86400E", isTargetHexColor: false },
      { hexColor: "#813B09", isTargetHexColor: false },
      { hexColor: "#7C3604", isTargetHexColor: false },
      { hexColor: "#773100", isTargetHexColor: false },
      { hexColor: "#722C00", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#DA70D6",
    difficulty: "hard",
    shades: [
      { hexColor: "#DA70D6", isTargetHexColor: true },
      { hexColor: "#D56BD1", isTargetHexColor: false },
      { hexColor: "#D066CC", isTargetHexColor: false },
      { hexColor: "#CB61C7", isTargetHexColor: false },
      { hexColor: "#C65CC2", isTargetHexColor: false },
      { hexColor: "#C157BD", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#7B68EE",
    difficulty: "hard",
    shades: [
      { hexColor: "#7B68EE", isTargetHexColor: true },
      { hexColor: "#7663E9", isTargetHexColor: false },
      { hexColor: "#715EE4", isTargetHexColor: false },
      { hexColor: "#6C59DF", isTargetHexColor: false },
      { hexColor: "#6754DA", isTargetHexColor: false },
      { hexColor: "#624FD5", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#6A5ACD",
    difficulty: "hard",
    shades: [
      { hexColor: "#6A5ACD", isTargetHexColor: true },
      { hexColor: "#6555C8", isTargetHexColor: false },
      { hexColor: "#6050C3", isTargetHexColor: false },
      { hexColor: "#5B4BBE", isTargetHexColor: false },
      { hexColor: "#5646B9", isTargetHexColor: false },
      { hexColor: "#5141B4", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#483D8B",
    difficulty: "hard",
    shades: [
      { hexColor: "#483D8B", isTargetHexColor: true },
      { hexColor: "#433886", isTargetHexColor: false },
      { hexColor: "#3E3381", isTargetHexColor: false },
      { hexColor: "#392E7C", isTargetHexColor: false },
      { hexColor: "#342977", isTargetHexColor: false },
      { hexColor: "#2F2472", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#008B8B",
    difficulty: "hard",
    shades: [
      { hexColor: "#008B8B", isTargetHexColor: true },
      { hexColor: "#008686", isTargetHexColor: false },
      { hexColor: "#008181", isTargetHexColor: false },
      { hexColor: "#007C7C", isTargetHexColor: false },
      { hexColor: "#007777", isTargetHexColor: false },
      { hexColor: "#007272", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#556B2F",
    difficulty: "hard",
    shades: [
      { hexColor: "#556B2F", isTargetHexColor: true },
      { hexColor: "#50662A", isTargetHexColor: false },
      { hexColor: "#4B6125", isTargetHexColor: false },
      { hexColor: "#465C20", isTargetHexColor: false },
      { hexColor: "#41571B", isTargetHexColor: false },
      { hexColor: "#3C5216", isTargetHexColor: false },
    ],
  },
  {
    targetHexColor: "#696969",
    difficulty: "hard",
    shades: [
      { hexColor: "#696969", isTargetHexColor: true },
      { hexColor: "#646464", isTargetHexColor: false },
      { hexColor: "#5F5F5F", isTargetHexColor: false },
      { hexColor: "#5A5A5A", isTargetHexColor: false },
      { hexColor: "#555555", isTargetHexColor: false },
      { hexColor: "#505050", isTargetHexColor: false },
    ],
  },
];